const NOT_FOUND_ERROR_CODE = 404;
const BAD_REQUEST_STATUS_CODE = 400;
const SERVER_ERROR_STATUS_CODE = 500;

module.exports = {
  BAD_REQUEST_STATUS_CODE,
  NOT_FOUND_ERROR_CODE,
  SERVER_ERROR_STATUS_CODE,
};
